managed/CounterStrikeSharp.API/Core/API.cs
managed/CounterStrikeSharp.API/Core/GameEvents.g.cs
managed/CounterStrikeSharp.API/Modules/Events/GameEvent.cs
managed/TestPlugin/TestPlugin.cs
tooling/CodeGen.Natives/Mapping.cs
tooling/CodeGen.Natives/Scripts/GenerateGameEvents.cs
tooling/CodeGen.Natives/Scripts/GenerateNatives.cs

improve generated event classes

---

managed/CounterStrikeSharp.API/Core/BasePlugin.cs
managed/CounterStrikeSharp.API/Core/PluginContext.cs

also now RegisterAttributeHandlers has parameter for which class to register handlers

a little code refactoring

---

managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs
managed/TestPlugin/TestPlugin.cs
tooling/CodeGen.Natives/Program.cs
tooling/CodeGen.Natives/Scripts/GenerateGameEvents.cs
tooling/CodeGen.Natives/Scripts/GenerateNativeObjects.cs

Generates native schema getters and setters for basic fields (int, float, bool, Vector, pointers)

Adds Code Generated Native Objects

---

INSTALL.md
docs/src/content/docs/guides/getting-started.md

Since we tested the Invariant globalization option without noticing any problems, here is the updated docs.

update docs about libicu / Invariant globalization

---

managed/TestPlugin/TestPlugin.cs

Update TestPlugin.cs, 

---

docs/src/content/docs/admin-framework/defining-admins.md
docs/src/content/docs/admin-framework/defining-groups.md

- Add STEAM_X:X;X example in Defing admins page
- Add information about admin admins to groups in Defining groups page
- Fix typo in defining groups page

Additional info admin module documentation

---

docs/src/content/docs/guides/hello-world-plugin.md

This comes after a conversation in the discord in which we identified that some files here are not necessary to upload as they are already included via CSS.
https://discord.com/channels/1160907911501991946/1160907912445710480/1179520129709641900
cc: @KillStr3aK

Improve plugin setup docs

---

README.md
docfx/layouts/cssharp/public/main.js

fix: discord links

---

docfx/index.md

This uses the secondary color and a different icon for the download button.
https://share.busheezy.dev/i/Jfdcbc
https://share.busheezy.dev/i/XJKDx9

CHANGE: visual adjustments

---

ACKNOWLEDGEMENTS
managed/CounterStrikeSharp.API/Core/Application.cs
src/core/cs2_sdk/interfaces/cschemasystem.h

Adds source2gen acknowledgement

chore: license updates

---

docfx/docs/guides/getting-started.md

The previous relative path didn't work, as it pointed to:
https://docs.cssharp.dev/docs/guides/images/gameinfogi-example.png

Fix getting started image

---

configs/addons/counterstrikesharp/gamedata/gamedata.json
managed/CounterStrikeSharp.API/Core/Model/CEntityInstance.cs
managed/CounterStrikeSharp.API/Modules/Memory/VirtualFunctions.cs
managed/TestPlugin/TestPlugin.cs

Based on WD-s provided code here: https://discord.com/channels/1160907911501991946/1175947333880524962/1189244426648825896
Closes #202

feat: add `AcceptInput` method to `CEntityInstance`

---

configs/addons/counterstrikesharp/gamedata/gamedata.json
managed/CounterStrikeSharp.API/Core/API.cs
managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs
managed/CounterStrikeSharp.API/Modules/Memory/VirtualFunctions.cs
managed/CounterStrikeSharp.API/Utilities.cs
managed/TestPlugin/TestPlugin.cs
src/scripting/natives/natives_schema.cpp
src/scripting/natives/natives_schema.yaml

Mimicking the functionality of [CS2Fixes](https://github.com/Source2ZE/CS2Fixes) and initial code by [Yarukon on Discord](https://discord.com/channels/1160907911501991946/1175947333880524962/1189178713628233748).

feat: add state changed and network state changed handler

---

managed/CounterStrikeSharp.API/Modules/Utils/ChatColors.cs

I kept the original value too since people may already be using it

Add DarkRed to ChatColors class to follow naming convention

---

.gitmodules
CMakeLists.txt
src/protobuf/compile.sh

chore: migrate to protobufs submodule

---

managed/CounterStrikeSharp.API/Core/Model/CCSGameRules.cs
managed/CounterStrikeSharp.API/Modules/Memory/VirtualFunctions.cs

Fix TerminateRound params

---

managed/CounterStrikeSharp.API/Modules/Entities/Constants/CollisionGroup.cs

fix: update collision groups

---

.github/workflows/cmake-single-platform.yml
.gitignore
makefiles/shared.cmake
managed/CounterStrikeSharp.API/Api.cs
managed/CounterStrikeSharp.API/Core/Application.cs
managed/CounterStrikeSharp.API/CounterStrikeSharp.API.csproj
src/mm_plugin.cpp

- Improves metamod version information
- Improves API version information
`meta list` now returns
```shell
Listing 1 plugin:
[01] CounterStrikeSharp (v199 @ 2b0923d) by Roflmuffin
```
`css` now returns
```shell
css
CounterStrikeSharp was created and is maintained by Michael "roflmuffin" Wilson.
Counter-Strike Sharp uses code borrowed from SourceMod, Source.Python, FiveM, Saul Rennison, source2gen and CS2Fixes.
See ACKNOWLEDGEMENTS.md for more information.
Current API Version: v199 (1.0.199+2b0923d)
```

feat: improve version stamping

---

configs/addons/counterstrikesharp/gamedata/gamedata.json
managed/CounterStrikeSharp.API/Core/API.cs
managed/CounterStrikeSharp.API/Core/Model/CEntityInstance.cs
managed/CounterStrikeSharp.API/Modules/Memory/VirtualFunctions.cs
managed/TestPlugin/TestPlugin.cs
src/core/managers/entity_manager.cpp
src/core/managers/entity_manager.h
src/scripting/natives/natives_entities.cpp
src/scripting/natives/natives_entities.yaml

(Might need to test on linux cuz i don't have linux enviroment)
Moved AcceptInput to NativeAPI, this change will fix #238
Added CEntitySystem_AddEntityIOEvent

AcceptInput changes

---

managed/CounterStrikeSharp.API/Core/Model/CBaseEntity.cs

- Use nullptr to handle the value that we don't want to change instead of reading from schema
- throw exception when all 3 arguments is null

Improve Teleport Function

---

src/core/function.cpp

Fix function hooking on windows

---

managed/CounterStrikeSharp.API/Core/Application.cs

Allows plugin unloading by file path, similar to `css_plugins load`
Closes #518

Improve plugin unloading consistency

---

configs/addons/counterstrikesharp/gamedata/gamedata.json
managed/CounterStrikeSharp.API/Modules/Memory/VirtualFunctions.cs

fix #540 
idk if the linux's pattern is working or not

Fix SetStateChanged

---

src/scripting/natives/natives_events.cpp

fix CreateEvent leak

---

managed/CounterStrikeSharp.API/Core/API.cs
managed/CounterStrikeSharp.API/Server.cs
src/scripting/natives/natives_engine.cpp
src/scripting/natives/natives_engine.yaml

GetGameframeTime was [registered](https://github.com/roflmuffin/CounterStrikeSharp/blob/ad7f7bd365d7080060acc94539830a9066cc4633/src/scripting/natives/natives_engine.cpp#L248) but not used

Add GetGameframeTime to NativeAPI

---

configs/addons/counterstrikesharp/gamedata/gamedata.json

Works on both Windows and Linux.

CCSPlayer_ItemServices_CanAcquire and GetCSWeaponDataFromKey signatures update

---

managed/CounterStrikeSharp.API/Modules/Utils/RecipientFilter.cs

With Bots Join Will Spam Errors
Code:
```
HookUserMessage(208, um =>
{
Server.PrintToConsole($"{um.DebugString}");
return HookResult.Continue; 
}, HookMode.Pre);
```
Before:
https://github.com/user-attachments/assets/39d13cc2-efbb-483d-8a93-6ba4f91e2a59
After:
https://github.com/user-attachments/assets/493e16f7-f69a-4555-a875-294a7de982f0

System.ArgumentException: Player with slot X not found

---

managed/CounterStrikeSharp.API/Modules/Commands/Targeting/Target.cs

https://github.com/roflmuffin/CounterStrikeSharp/issues/610

fix: `ArgumentOutOfRangeException` when calling `GetArgTargetResult`

---

configs/addons/counterstrikesharp/gamedata/gamedata.json

Fix `EmitSoundFilter` signature for linux

---

configs/addons/counterstrikesharp/gamedata/gamedata.json

by [Javierko](https://github.com/Javierko)

Update CCSPlayer_ItemServices_CanAcquire signature

---

.gitmodules
src/core/managers/entity_manager.cpp
src/core/managers/entity_manager.h
src/core/recipientfilters.h
src/scripting/natives/natives_commands.cpp
src/scripting/natives/natives_engine.cpp
src/scripting/natives/natives_entities.cpp
src/scripting/natives/natives_usermessages.cpp

Revert hl2sdk back to Alliedmodders

chore: apply alliedmodders hl2sdk again
