managed/CounterStrikeSharp.API/Core/GameEvents.g.cs
managed/CounterStrikeSharp.API/Modules/Events/GameEvent.cs
managed/TestPlugin/TestPlugin.cs
tooling/CodeGen.Natives/Mapping.cs
tooling/CodeGen.Natives/Scripts/GenerateGameEvents.cs

- Changes generated game event code to use a generic `Get<T>` and `Set<T>` under the hood.
- Makes all event value accessors protected (forces use of the generic methods)
- Removes type mapping cruft from the code generator and instead moves it into the runtime set/get

feat: improve generic typing of GameEvent

---

managed/CounterStrikeSharp.API/Core/API.cs
managed/CounterStrikeSharp.API/Core/Model/CEntityInstance.cs
managed/CounterStrikeSharp.API/Utilities.cs
managed/TestPlugin/TestPlugin.cs
src/scripting/natives/natives_entities.cpp
src/scripting/natives/natives_entities.yaml

The goal of this PR is to add a function that allows plugins to grab a list of all entities with a certain design name so they can be easily manipulated. The example I've used is setting all of the player's money value to 1337.
This could be optimized, but this will require further work internally which I'm not confident with. Right now the function loops through all 16k entity indexes, but this can probably be cut down using the method [CS2Fixes uses by navigating through entity pointers until they run into a null pointer](https://github.com/Source2ZE/CS2Fixes/blob/main/src/utils/entity.cpp#L29). It would be possible to do the basic functionality on the C++ side, but I prefer the design of returning a List, and returning an array from the C++ side isn't easy as I've been told. A feature …

Add helper function FindAllEntitiesByDesignerName

---

.clang-format
.clang-tidy
docs/src/content/docs/features/game-events.md
docs/src/content/docs/index.mdx
makefiles/linux.base.cmake
managed/CounterStrikeSharp.API/Core/BasePlugin.cs
managed/CounterStrikeSharp.API/Core/GameEventInfo.cs
managed/CounterStrikeSharp.API/Core/GameEvents.g.cs
managed/CounterStrikeSharp.API/Core/HookResult.cs
managed/CounterStrikeSharp.API/Modules/Events/GameEvent.cs
managed/TestPlugin/TestPlugin.cs
src/core/managers/event_manager.cpp
src/core/managers/event_manager.h
src/scripting/callback_manager.cpp
src/scripting/callback_manager.h
src/scripting/script_engine.h
tooling/CodeGen.Natives/Scripts/GenerateGameEvents.cs

Changes the way the event manager executes event callbacks so that a plugin can return a `HookResult`, similar to Sourcemods `Plugin_Handled` or `Plugin_Continue` which will prevent propagation of the event to other plugins.
Also provides a second parameter to event handlers called `info` which contains a single `ref bool` which allows you to modify the `DontBroadcast` flag on an event. If you set this to `true` in an event handler, it will prevent the event from being sent to clients. If you set `DontBroadcast = true` on the `player_death` event for instance, there will be no kill in the killfeed.

Game Event Broadcast Manipulation & Cancellation

---

INSTALL.md
docs/src/content/docs/guides/getting-started.md

when using docker (debian bullseye) to run CounterStrikeSharp, the process terminates with the error
```
[19:03:34.187] CSSharp: .NET Runtime Initialised.
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu (or icu-libs) using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
at System.Environment.FailFast(System.String)
at System.Globalization.GlobalizationMode+Settings..cctor()
at System.Globalization.CultureData.CreateCultureWithInvariantData()
at System.Globalization.CultureData.get_Invariant()
at System.Globalization.CultureInfo..cctor()
at …
```

add libicu readme hint

---

managed/CounterStrikeSharp.API/Core/GlobalContext.cs
managed/CounterStrikeSharp.API/Core/Helpers.cs
managed/CounterStrikeSharp.API/Core/PluginContext.cs
managed/CounterStrikeSharp.API/Utilities.cs

This PR adds two new commands: `css`, and `css_plugins`.
- `css` displays credits (mainly towards roflmuffin) and points towards the acknowledgements file.
- `css_plugins` handles plugin loading, unloading, reloading, and displaying a list of plugins.
I've also moved a few things around in `GlobalContext`: renamed `LoadAll` to `InitGlobalContext`, and split some functions into smaller ones.
I decided to deviate from the MetaMod/SourceMod style of "self-command" and split plugins into it's own isolated category of commands. I did this for future development, like possibly incooperating `apfelwurm` 's [update/install commands](https://discord.com/channels/1160907911501991946/1160907912445710481/1166516777925222400) into it's own category.

Add css, css_plugins commands.

---

managed/CounterStrikeSharp.API/Core/GlobalContext.cs

Is this okay here, or would you prefer we add an additional command `css_version`?

feat: Add Current API Version to css console command

---

managed/CounterStrikeSharp.API/Modules/Admin/AdminPermissions.cs

Quick little hotfix after the AdminManager update.
Users would define admins in `configs/admins.json` without the `flags` array and instead have flags inherited from `configs/admins_groups.json`. This PR removes the `required` keyword from the AdminData code. The only place that now requires flags is in `configs/admin_groups.json`.

Remove required from flags in AdminData

---

managed/CounterStrikeSharp.API/Core/BasePlugin.cs
managed/CounterStrikeSharp.API/Core/CoreConfig.cs
managed/CounterStrikeSharp.API/Core/FunctionReference.cs
managed/CounterStrikeSharp.API/Core/GameData.cs
managed/CounterStrikeSharp.API/Core/GlobalContext.cs
managed/CounterStrikeSharp.API/Core/Logging/CoreLogging.cs
managed/CounterStrikeSharp.API/Core/Logging/PluginLogging.cs
managed/CounterStrikeSharp.API/Core/Logging/PluginNameEnricher.cs
managed/CounterStrikeSharp.API/Core/Logging/SourceContextEnricher.cs
managed/CounterStrikeSharp.API/Core/PluginContext.cs
managed/CounterStrikeSharp.API/Core/ScriptContext.cs
managed/CounterStrikeSharp.API/CounterStrikeSharp.API.csproj
managed/CounterStrikeSharp.API/Modules/Admin/AdminManager.cs
managed/CounterStrikeSharp.API/Modules/Config/ConfigManager.cs
managed/CounterStrikeSharp.API/Modules/Memory/DataType.cs
managed/TestPlugin/TestPlugin.cs

- Adds two new logger factories which are used for core logging & plugin logging. 
- Adds a static `ILogger` to the global context instance for use in general core logging.
- Adds an `ILogger` property to the `BasePlugin` class for use by plugins.
- Logs log to file in three suffixes, `all` for all logs (plugin and core), `{PluginName}` for plugin specific logs, and `cssharp` for core specific logs.
- One logger is created per plugin instance; though this could be done through the use of a service collection later.
- Loggers are not configurable through config files yet
e.g.
```sh
log-all20231116.txt
log-all20231119.txt
log-cssharp20231118.txt
log-SamplePlugin20231116.txt
```

Managed Core Logging & Plugin Logging

---

docs/src/content/docs/features/game-events.md

This fixes the main example in the current documentation that showcases how to work with game events.  Right now, that code example will consistently trigger runtime exceptions.
This PR will fix the code example and also educates the user reading the documentation why that is required.
Fixes https://github.com/roflmuffin/CounterStrikeSharp/issues/26.

Check if userid is valid before accessing its fields, and explain why

---

managed/CounterStrikeSharp.API/Modules/Entities/Constants/SteamAccountInstance.cs
managed/CounterStrikeSharp.API/Modules/Entities/Constants/SteamAccountType.cs
managed/CounterStrikeSharp.API/Modules/Entities/Constants/SteamAccountUniverse.cs
managed/CounterStrikeSharp.API/Modules/Entities/SteamID.cs

**Update:**
Added support for
* AccountId
* AccountInstance
* AccountType
* AccountUniverse
Which also allows for` IsValid()` check and `ToCommunityUrl()`
**Tests:**
```
[SteamID 76561197960524373, STEAM_0:1:129322, [U:1:258645]]
Valid: True
AccountId: 258645
AccountType: Individual
AccountInstance: Desktop
AccountUniverse: Public
```
```
[SteamID 0, STEAM_0:0:9185091437874642944, [I:0:18370182875749285888]]
Valid: False
AccountId: 0
AccountType: Invalid
AccountInstance: All
AccountUniverse: Invalid
```
```
[SteamID 76561197960265728, STEAM_0:0:0, [U:1:0]]
Valid: False
AccountId: 0
AccountType: Individual
AccountInstance: Desktop
AccountUniverse: Public
```
```
[SteamID 103582791429521412, STEAM_0:0:13510796734627842, [g:1:27021593469255684]]
Valid: True
AccountId: 4
AccountType: Clan …
```

Enriched SteamID

---

CMakeLists.txt
configs/addons/counterstrikesharp/gamedata/gamedata.json
managed/CounterStrikeSharp.API/Core/API.cs
managed/CounterStrikeSharp.API/Core/Attributes/Registration/EntityOutputHookAttribute.cs
managed/CounterStrikeSharp.API/Core/BasePlugin.cs
managed/CounterStrikeSharp.API/Modules/Entities/EntityIO.cs
managed/TestPlugin/TestPlugin.cs
src/core/managers/entity_manager.cpp
src/core/managers/entity_manager.h
src/scripting/natives/natives_entities.cpp
src/scripting/natives/natives_entities.yaml

This pull requests implements the ability to hook entity outputs for a given classname or entity.
```c#
public override void Load(bool hotReload)
{
HookEntityOutput("weapon_knife", "OnPlayerPickup", (string name, CEntityInstance activator, CEntityInstance caller, float delay) =>
{
Logger.LogInformation("weapon_knife called OnPlayerPickup ({name}, {activator}, {caller}, {delay})", name, activator.DesignerName, caller.DesignerName, delay);
});
}
```
```c#
[EntityOutputHook("weapon_knife", "OnPlayerPickup")]
public void OnKnifePickup(string name, CEntityInstance activator, CEntityInstance caller, float delay)
{
Logger.LogInformation("[EntityOutputHook Attribute] weapon_knife called OnPlayerPickup ({name}, {activator}, {caller}, {delay})", name, activator.DesignerName, caller.DesignerName, …
```

feat: Add entity output hooking

---

managed/TestPlugin/TestPlugin.cs
src/core/global_listener.h
src/core/globals.cpp
src/core/globals.h
src/core/managers/event_manager.cpp
src/core/managers/event_manager.h
src/mm_plugin.cpp
src/mm_plugin.h

The `Load` method of plugins (and CS#) is before game loop starts, which I believe includes other services. You can see in the console of startup that the events file is only loaded *after* CS#. This change defers all calls to `HookEvent` in a queue and registers them once the game loop mode is registered. Fixes #140

feat: defers calls to `HookEvent` until after game loop mode init

---

managed/CounterStrikeSharp.API/Core/GameData.cs

This pull request aims to add custom gamedata functionality to CounterStrikeSharp.
Currently you can only add custom offsets/signatures by editing the included gamedata.json file. This change adds the ability to make additional json files in the gamedata directory and have them loaded.
This is beneficial when you want to add offsets/signatures that are not default to CSSharp and want to avoid having to update gamedata.json every time you update CSSharp...
Proof of functionality:

feat: Added support for custom gamedata files.

---

docfx/docs/guides/getting-started.md

Since CSS now supports translations, icu lib is required.

Docs: Using DOTNET_SYSTEM_GLOBALIZATION_INVARIANT is no longer valid.

---

managed/CounterStrikeSharp.API/Utilities.cs

I was caught out by doing `player.RemoveItemByDesignerName("weapon_c4");`, it removed the item from the players inventory but didn't remove the entity.
Here's a PR to allow people to specify whether or not they would like to also remove the entity.
New usage:
`player.RemoveItemByDesignerName("weapon_c4", true);`

Added a parameter for people to optionally remove the entity when calling RemoveItemByDesignerName

---

managed/CounterStrikeSharp.API/Core/Model/CCSPlayerController.cs

This means that people don't have to constantly cast the `player.TeamNum` to CsTeam in their plugins.

Add casted property .Team to CCSPlayerController

---

managed/CounterStrikeSharp.API.Tests/AdminTests.cs
managed/CounterStrikeSharp.API/Modules/Admin/AdminGroup.cs
managed/CounterStrikeSharp.API/Modules/Admin/AdminPermissions.cs
managed/CounterStrikeSharp.API/Modules/Commands/Targeting/Target.cs

A few additions after a conversation on Discord:
- Updated comments for AddPlayerToGroup 
- Added player controller equivalent for GetPlayerAdminData and RemovePlayerAdminData
- Added GetPlayerImmunity
- Prevent HLTV player controller from being passed into admin-related functions
- Changed TargetType.GroupAll TargetPredicate to exclude HLTV
I've decided to exclude the HLTV player from these functions as they do not have a physical presence in the world and shouldn't be manipulated with commands.

Admin manager improvements

---

configs/addons/counterstrikesharp/gamedata/gamedata.json

Fixes #250 
It looks like the windows VTable is padded with some random values, which the 21 offset was trying to hook, leading to the MemoryAccess Exceptions.

fix(Offsets/Win): CCSPlayer_ItemServices.RemoveWeapons()

---

managed/CounterStrikeSharp.API/Core/Application.cs

I've realized this might be missing.
Caught me as i was mostly hot-reloading my plugins during development.

Log exception if plugin load fails using the `load` command

---

managed/CounterStrikeSharp.API/Modules/Menu/BaseMenu.cs
managed/CounterStrikeSharp.API/Modules/Menu/CenterHtmlMenu.cs
managed/CounterStrikeSharp.API/Modules/Menu/ChatMenu.cs
managed/CounterStrikeSharp.API/Modules/Menu/ConsoleMenu.cs
managed/CounterStrikeSharp.API/Modules/Menu/IMenu.cs
managed/CounterStrikeSharp.API/Modules/Menu/MenuManager.cs

Allow plugins to close the active menu in the MenuManager, also updated OnKeyPress to utilise the GetActiveMenu function and added the .Close() function to a base menu instance

Improved menu closing

---

managed/CounterStrikeSharp.API/Core/API.cs
managed/CounterStrikeSharp.API/Core/Application.cs
managed/CounterStrikeSharp.API/Modules/Commands/CommandCallingContext.cs
managed/CounterStrikeSharp.API/Modules/Commands/CommandInfo.cs
managed/TestPlugin/TestPlugin.cs
src/core/managers/chat_manager.cpp
src/core/managers/con_command_manager.cpp
src/core/managers/con_command_manager.h
src/core/managers/player_manager.cpp
src/scripting/natives/natives_commands.cpp
src/scripting/natives/natives_commands.yaml
tooling/CodeGen.Natives/Mapping.cs
tooling/CodeGen.Natives/Scripts/GenerateNatives.cs

Adds command context (chat or console) to `CommandInfo` so it can be used to determine where `ReplyToCommand` should send the message automatically. This deprecates the overloaded `console = true` default param for existing `ReplyToCommand`.
Closes #77

feat: add CommandCallingContext to commands

---

managed/CounterStrikeSharp.API/Core/Schema/Classes/CBaseIssue.g.cs
managed/CounterStrikeSharp.API/Core/Schema/Classes/CBasePlayerController.g.cs
managed/CounterStrikeSharp.API/Core/Schema/Classes/CCSBot.g.cs
managed/CounterStrikeSharp.API/Core/Schema/Classes/CCSGameRules.g.cs
managed/CounterStrikeSharp.API/Core/Schema/Classes/CCSPlayerController.g.cs
managed/CounterStrikeSharp.API/Core/Schema/Classes/CCSPlayerPawn.g.cs
managed/CounterStrikeSharp.API/Core/Schema/Classes/CCSPlayerPawnBase.g.cs
managed/CounterStrikeSharp.API/Core/Schema/Classes/CCSTeam.g.cs
managed/CounterStrikeSharp.API/Core/Schema/Classes/CColorCorrection.g.cs
managed/CounterStrikeSharp.API/Core/Schema/Classes/CColorCorrectionVolume.g.cs
managed/CounterStrikeSharp.API/Core/Schema/Classes/CEconItemView.g.cs
managed/CounterStrikeSharp.API/Core/Schema/Classes/CEnvMicrophone.g.cs
managed/CounterStrikeSharp.API/Core/Schema/Classes/CEnvProjectedTexture.g.cs
managed/CounterStrikeSharp.API/Core/Schema/Classes/CGameRules.g.cs
managed/CounterStrikeSharp.API/Core/Schema/Classes/CParticleSystem.g.cs
managed/CounterStrikeSharp.API/Core/Schema/Classes/CPlayerPing.g.cs
managed/CounterStrikeSharp.API/Core/Schema/Classes/CPointClientUIWorldTextPanel.g.cs
managed/CounterStrikeSharp.API/Core/Schema/Classes/CPointWorldText.g.cs
managed/CounterStrikeSharp.API/Core/Schema/Classes/CTeam.g.cs
managed/CounterStrikeSharp.API/Core/Schema/Classes/CTriggerSndSosOpvar.g.cs
managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs
managed/CounterStrikeSharp.SchemaGen/Program.cs

Properly handles string Schema property setters that are using simple char arrays, e.g. `char m_iszPlayerName[128]`
Fixes #45

fix: handle byte array schema properties correctly

---

managed/CounterStrikeSharp.API/Modules/Extensions/PlayerExtensions.cs
managed/CounterStrikeSharp.API/Modules/Extensions/TeamExtensions.cs
managed/CounterStrikeSharp.API/Modules/Utils/ChatColors.cs

Adds new method & extension methods, credit to @busheezy for fetching a players chat color.
`ChatColors.ForPlayer(player);`
`player.GetChatColor();`
`player.Team.GetChatColor();`
Closes #161

feat: add chat color method for player controller

---

managed/CounterStrikeSharp.API/Core/Model/CBaseEntity.cs
managed/CounterStrikeSharp.API/Core/Model/CBaseModelEntity.cs
managed/CounterStrikeSharp.API/Core/Model/CBasePlayerController.cs
managed/CounterStrikeSharp.API/Core/Model/CBasePlayerPawn.cs
managed/CounterStrikeSharp.API/Core/Model/CCSPlayerController.cs
managed/CounterStrikeSharp.API/Core/Model/CCSPlayer_ItemServices.cs
managed/CounterStrikeSharp.API/Core/Model/CEntityInstance.cs
managed/CounterStrikeSharp.API/Core/Model/CGameSceneNode.cs
managed/CounterStrikeSharp.API/Guard.cs
managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs
managed/CounterStrikeSharp.API/Utilities.cs
src/scripting/natives/natives_entities.cpp

As of right now cs# isn't very strict about the values the API works with, this allows for edge cases that can lead to server crashes. This PR adds the most basic checks to prevent obviously wrong arguments.
Note for developers using cs#
Please do report code that causes unexpected crashes or memory access violations, no code exposed by cs# should ever lead to a server crash.

feat: improve entity validation

---

managed/CounterStrikeSharp.API.Tests/AdminTests.cs
managed/CounterStrikeSharp.API/Modules/Admin/AdminCommandOverrides.cs

This is currently preventing a valid use. If someone wants to entirely remove flag requirements of a command with overrides, they would be unable to.

fix: allow using an empty flag array in overrides

---

libraries/moodycamel/concurrentqueue.h
makefiles/shared.cmake
managed/CounterStrikeSharp.API/CompatibilitySuppressions.xml
managed/CounterStrikeSharp.API/Core/FunctionReference.cs
managed/CounterStrikeSharp.API/GlobalUsings.cs
managed/CounterStrikeSharp.API/Server.cs
src/core/managers/server_manager.cpp
src/core/managers/server_manager.h
src/mm_plugin.cpp
src/mm_plugin.h

- Uses MPMC queue for frame related tasks, which allows nested next frame calls and processes up to 1024 tasks per frame.
- Adds Task completion to next frame helpers, which allows them to be used in an async context and awaited which provides more reasonable behaviour.
- Fixes thread safety of `FunctionReference` identifiers, as these were not behind a lock, so multiple threads creating new function references (i.e. `Server.NextFrame`) would cause id dictionary collisions and garbage collector would free the underlying callback, causing a crash.
- Forces a new callback for all `FunctionReference` created with a single use lifetime, previously if your lambda was re-used (and did not capture variables), it would be looked up in a dictionary and the same function callback would be used, …

feat: use concurrent queue for next frame & world update tasks

---

CMakeLists.txt
managed/CounterStrikeSharp.API/CompatibilitySuppressions.xml
managed/CounterStrikeSharp.API/Core/API.cs
managed/CounterStrikeSharp.API/Server.cs
src/core/globals.cpp
src/core/globals.h
src/core/tick_scheduler.cpp
src/core/tick_scheduler.h
src/mm_plugin.cpp
src/scripting/natives/natives_engine.cpp
src/scripting/natives/natives_engine.yaml

Adds `RunOnTick` and `RunOnTickAsync` methods which allow you to queue a task for a specific game frame. Closes #367 
Example usage:
```csharp
Server.RunOnTick(Server.TickCount + 64, () => Console.WriteLine("Hello World"));
```
The async overload simply returns a `Task` which can be awaited which resolves once the callback has executed.

feat: add `Server.RunOnTick` method which allows tick scheduling

---

managed/CounterStrikeSharp.API/Core/API.cs
managed/CounterStrikeSharp.API/Core/Model/NetworkedVector.cs
src/scripting/natives/natives_memory.cpp

This PR adds the `RemoveAll` method to `NetworkedVector` class.

Add `RemoveAll` method to `NetworkedVector` class

---

managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/DynamicHook.cs

Re-add the unused parameter with a overload because it breaks plugins not updated to also remove said parameter

Fix backwards compatibility in DynamicHook

---

managed/CounterStrikeSharp.API/Modules/Menu/CenterHtmlMenu.cs

fix: mark center html menu constructor as obsolete, throw error

---

.clang-format
.editorconfig
.gitignore
.vscode/settings.json
eng/formatting/download-tools.ps1
eng/formatting/download-tools.sh
eng/formatting/format.sh

- Update .clang-format with more prescriptive rules
- Add scripts to download a local copy of clang-format
- Add basic .editorconfig with line ending and spacing configuration
- Add format on save vscode workspace settings

Update .clang-format & add formatting tool install scripts

---

managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs

I propose this change as I don't think we should be this strict when we are loading shared types.
Currently when a shared type is loaded it is saved with assembly build version and plugins that depends on other shared type(s) cannot be loaded if the shared type version has changed, even if there are no breaking changes as the shared type just cannot be found at all (or version mismatch)
this pr changes this behaviour and it only looks for the shared type name and loads it, I believe developers should be aware of the changes of the shared type they depend on, just like how it works with the core api.

Make shared type loader less strict

---

configs/addons/counterstrikesharp/gamedata/gamedata.json
managed/CounterStrikeSharp.API/Core/Model/CCSPlayerController.cs
managed/CounterStrikeSharp.API/Core/Model/CCSPlayer_ItemServices.cs

- Adds offsets for GiveNamedItem
- Adds method to `CCSPlayer_ItemServices`
- Updates method in `CCSPlayerController` to use this new method
- Adds generic overload for GiveNamedItem which accepts `T : CEntityInstance`, so you can do `player.GiveNamedItem<CCSWeaponBaseGun>("weapon_ak47");` and get the proper type back.

chore: use offsets for give named item

---

configs/addons/counterstrikesharp/gamedata/gamedata.json

need those who use linux to test this to see if the crash still occur
(i dont have linux enviroment to test this rn)
how to test:
try precache something and then change map

Fix AddResource offset for Linux

---

README.md

Every other example as far as i've seen uses "css_" as prefix except from this one

Change example command prefix to follow "best practice"

---

managed/CounterStrikeSharp.API/Core/CoreConfig.cs

Fixes the following exception if `core.json` is not found
```
15:35:23 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.ArgumentNullException: Value cannot be null. (Parameter 'value')
at System.ArgumentNullException.Throw(String paramName)
at System.Globalization.CultureInfo.set_CurrentCulture(CultureInfo value)
at CounterStrikeSharp.API.Core.Translations.WithTemporaryCulture.SetCulture(CultureInfo cultureInfo) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/WithTemporaryCulture.cs:line 17
at CounterStrikeSharp.API.Core.Translations.WithTemporaryCulture..ctor(CultureInfo culture) in …
```

CoreConfig: Prevent "Error invoking callback" if core.json not found

---

src/core/UserMessage.h
src/scripting/natives/natives_usermessages.cpp

This should fix the use case below
```C#
public HookResult Hook_WeaponFiring(UserMessage userMessage)
{
var weaponid = userMessage.ReadUInt("weapon_id");
var soundType = userMessage.ReadInt("sound_type");
var itemdefindex = userMessage.ReadUInt("item_def_index");
userMessage.SetUInt("weapon_id", 0);
userMessage.SetInt("sound_type", 9);
userMessage.SetUInt("item_def_index", 61);
// send for people who use silencer.
userMessage.Recipients = new(silencer);
userMessage.Send();
userMessage.SetUInt("weapon_id", weaponid);
userMessage.SetInt("sound_type", soundType);
userMessage.SetUInt("item_def_index", itemdefindex);
userMessage.Recipients = new(normal);
return HookResult.Continue;
}
```
Code is from [https://github.com/oylsister/StopSound/commit/95998e32d630a0f016c5b2f60d6d166e224c2a30](https: …

Fix calling Send using UM instance from UM hook

---

managed/CounterStrikeSharp.API/Core/Commands/CommandManager.cs

This PR fixes a scenario where a command calls BasePlugin::RemoveCommand for its own callback; currently, an InvalidOperationException is thrown. See the sample plugin below.
```c#
using CounterStrikeSharp.API.Core;
using CounterStrikeSharp.API.Modules.Commands;
namespace SamplePlugin;
public class SamplePlugin : BasePlugin
{
public override string ModuleName => "SamplePlugin";
public override string ModuleVersion => "0.0.1";
public override void Load(bool hotReload)
{
AddCommand("css_print_once", "Prints message once.", OnPrintOnceCommand);
}
public void OnPrintOnceCommand(CCSPlayerController? controller, CommandInfo _)
{
controller?.PrintToChat($"Hello, World!");
RemoveCommand("css_print_once", OnPrintOnceCommand);
}
}
```

fix: `InvalidOperationException` when removing command in its callback

---

managed/CounterStrikeSharp.API/Core/Model/CTakeDamageInfo.cs
managed/CounterStrikeSharp.API/Core/Schema/Classes/CTakeDamageInfo.g.cs

```csharp
public static HookResult OnTakeDamage(DynamicHook hook)
{
CEntityInstance entity = hook.GetParam<CEntityInstance>(0);
if (entity.DesignerName != "player")
{
return HookResult.Continue;
}
var info = hook.GetParam<CTakeDamageInfo>(1);
Server.PrintToChatAll($"HEY {info.Attacker.Value?.DesignerName} -> {info.GetHitGroup()}");
return HookResult.Continue;
}
```

Added hitgroup to CTakeDamageInfo

---

src/core/timer_system.cpp

Fix RemoveMapChangeTimers 

---

managed/CounterStrikeSharp.API/Core/Model/NetworkedVector.cs
src/scripting/natives/natives_memory.cpp

as the title said
only tested QAngle but Vector should work fine

Make NetworkedVector support Vector and QAngle

---

managed/CounterStrikeSharp.API/Modules/Cvars/FakeConVar.cs

When trying to set URLs into `FakeConVar`s, the server doesn't parse it properly.
```sh
my_string_convar https://example.com
my_string_convar "https://example.com"
```
After this PR, the second case should work as expected. The first case seems to be the way the server parses the argument once we send the command, so nothing much we can do about it. The value needs to be wrapped into quotes to be extracted from them.
```sh
my_string_convar https://example.com
my_string_convar "https://example.com"
```

feat: handle quotes for `FakeConVar<string>`

---

managed/CounterStrikeSharp.API/Modules/Menu/CenterHtmlMenu.cs

Remove the characters limit for CenterHtmlMenu

---

managed/CounterStrikeSharp.API/Core/API.cs
managed/CounterStrikeSharp.API/Core/Model/CCSPlayerController.cs
src/scripting/natives/natives_commands.cpp
src/scripting/natives/natives_commands.yaml

This PR is based on https://github.com/roflmuffin/CounterStrikeSharp/pull/563 but I have removed the client checks (as they are not necessary) which makes this easier to maintain.
I have tested and validated that everything works correctly on Linux, the core `ReplicateConVar` code is also identical to the implementation in CS2Fixes (https://github.com/Source2ZE/CS2Fixes/blob/e9dfd9a08b7158c313221019d34e8586a6396d5a/src/playermanager.cpp#L567-L580) and uses all the same features which `UserMessage` already relies on, no additional signatures or offsets.
I have tested this with `sv_autobunnyhopping` and `sv_enablebunnyhopping` using the plugin below to enable bhop on a per player basis and I have not encountered any issues, I tested this with a friend to ensure it was properly setting per …

feat: add ReplicateConVar

---

CMakeLists.txt
managed/CounterStrikeSharp.API/Core/API.cs
managed/CounterStrikeSharp.API/Core/GameEvents.g.cs
managed/CounterStrikeSharp.API/Core/Listeners.g.cs
managed/CounterStrikeSharp.API/Utilities.cs
src/mm_plugin.cpp
src/mm_plugin.h
src/scripting/listeners/metamod.yaml
src/scripting/natives/natives_metamod.cpp
src/scripting/natives/natives_metamod.yaml

This PR can expose the function `MetaFactory` and the listener `AllPluginsLoaded` in metamod to the cssharp API, which enable user to have a basic way to interact with metamod plugins without using p/invoke.
- NativeAPI: `IntPtr NativeAPI.MetaFactory(pInterfaceName);`
- Utilities: `IntPtr? Utilities.MetaFactory(pInterfaceName);`
- Listener: `Listeners.OnMetamodAllPluginsLoaded`
Here's an example usage:
```csharp
RegisterListener<Listeners.OnMetamodAllPluginsLoaded>(() => {
nint? pMultiAddonManager = Utilities.MetaFactory("MultiAddonManager002");
if (!pMultiAddonManager.HasValue) {
Console.WriteLine("Multiaddonmanager not installed!");
return;
}
var RefreshAddons = VirtualFunction.CreateVoid<IntPtr>(pMultiAddonManager.Value, 4);
RefreshAddons.Invoke(pMultiAddonManager.Value);
});
```

feat: Expose `MetaFactory` to API

---

managed/CounterStrikeSharp.API/Core/GameEvents.g.cs
managed/TestPlugin/TestPlugin.cs
tooling/CodeGen.Natives/Scripts/GenerateGameEvents.cs

note: this is a breaking change against `player_chat.userid` as it has gone from `int` to `CCSPlayerController`.

fix(gameevents): promote `core.gameevents` to have higher priority

---

src/scripting/natives/natives_events.cpp

Fixes some potential cases where the passed in `game_event` or `pListener` is null and causes a crash.

Fix potential event natives crashes

---

CMakeLists.txt
configs/addons/counterstrikesharp/configs/core.example.json
docfx/docs/reference/core-configuration.md
libraries/httplib/httplib.h
makefiles/linux.base.cmake
makefiles/windows.base.cmake
managed/CounterStrikeSharp.API/Core/CoreConfig.cs
src/core/coreconfig.cpp
src/core/coreconfig.h
src/core/gameconfig_updater.cpp
src/core/gameconfig_updater.h
src/mm_plugin.cpp

Adds a basic automatic gamedata update system which will check the latest gamedata.json file from a CDN and download the new gamedata file if the ETag is different.

feat: Add Automatic Gamedata Updates

---

managed/CounterStrikeSharp.API/Core/Listeners.g.cs
src/core/game_system.cpp
src/core/game_system.h
src/core/managers/server_manager.cpp
src/core/managers/server_manager.h

Adds new listeners for pre and post think frame hooks

feat: add `OnServerPreEntityThink` and `OnServerPostEntityThink`

---

managed/CounterStrikeSharp.API/Core/Model/CBaseEntity.cs
managed/CounterStrikeSharp.API/Modules/Utils/QAngle.cs
managed/CounterStrikeSharp.API/Modules/Utils/Vector.cs

Since `Teleport` is probably the biggest source of Vector based memory leaks, this adds a way to call the Teleport virtual method using `System.Numerics.Vector3` while still maintaining backwards compatibility.
To increase the ergonomics of modifying existing vectors coming out of the schema system (like with AbsOrigin), I've added explicit cast operators to allow you to easily convert to a numerics Vector3. This means the following code can be substituted to remove memory leak:
Before:
```cs
// Leaks because 2021 Roflmuffin sucks and `new Vector` allocates memory in native side and never frees it
pawn.Teleport(new Vector(pawn.AbsOrigin.X, pawn.AbsOrigin.Y, pawn.AbsOrigin.Z + 100));
```
After:
```cs
// Doesn't leak because the Vector3 is a struct and the pointer passed directly to native …
```

feat: add Vector3 and QAngle explicit casts to System.Numerics.Vector3

---

managed/CounterStrikeSharp.API/Core/Listeners.g.cs
src/core/managers/chat_manager.cpp
src/core/managers/chat_manager.h

Replaces the old `player_chat` hacky game event with an actual listener so we aren't tied to valve game events.

feat: add `OnPlayerChat` listener

---

configs/addons/counterstrikesharp/gamedata/gamedata.json
managed/CounterStrikeSharp.API/Core/API.cs
managed/CounterStrikeSharp.API/Modules/Memory/VirtualFunctions.cs
managed/CounterStrikeSharp.API/Modules/Utils/ResourceManifest.cs
managed/CounterStrikeSharp.API/Server.cs
src/core/game_system.cpp
src/core/game_system.h
src/scripting/natives/natives_engine.cpp
src/scripting/natives/natives_engine.yaml

- Signature Updates
- Updated to latest CS2 SDK
@stefanx111  mentioned that ``GetCSWeaponDataFromKey`` got new 5 parameters for this function in discord.
https://discord.com/channels/1160907911501991946/1160907912445710479/1417655472512827392

Update CS2 09-17-25

---

managed/CounterStrikeSharp.API/CompatibilitySuppressions.xml
managed/CounterStrikeSharp.API/Modules/Extensions/CBasePlayerWeaponExtensions.cs
managed/CounterStrikeSharp.API/Server.cs
managed/CounterStrikeSharp.API/Utilities.cs

- feat: add CBasePlayerWeaponExtensions with GetWeaponName and GetOwner
- feat: optimize MaxPlayers by replacing Lazy<T> with static readonly int
- feat: improve GetPlayers performance and RemoveItemByDesignerName reliability
- feat: add RemoveItemBySlot
Not tested

feat: improve getplayers & RemoveItemByDesignerName
